const path = require("path");

/**
 * Helper class that allows to easily retrieve data in an JSON info set
 * generated by Bronze.
 */
class BronzeHelper {
  constructor(data) {
    if(typeof data !== "object") {
      throw new Error("BronzeHelper: data must be an object.");
    }

    this.data = data;
  }

  /**
   * Returns a profile info object and checks that it exists.
   */
  getProfile(name) {
    if(!name) name = "DEFAULT"; // Assume default profile name.
    if(this.data.hasOwnProperty(name))
      return this.data[name];
    else
      throw new Error(`BronzeHelper: profile ${name} not found.`);
  }

  /**
   * Returns an image info object and checks that it exists.
   */
  getImage(id, profile) {
    let p = this.getProfile(profile);
    if(p.images.hasOwnProperty(id))
      return p.images[id];
    else
      throw new Error(`BronzeHelper: image ${id} not found in profile ${profile}.`);
  }

  /**
   * Returns all the versions of an image in a given format.
   */
  getVersionsByFormat(id, format, profile) {
    let img = this.getImage(id, profile);
    if(!img.indexByFormat.hasOwnProperty(format))
      throw new Error(`BronzeHelper: format ${format} not present for image ${id} in profile ${profile}.`);

    let r = [];
    img.indexByFormat[format].forEach(index => {
      r.push(img.versions[index]);
    });

    return r;
  }

  /**
   * Returns all the versions of an image from a given transform.
   */
  getVersionsByTransform(id, transform, profile) {
    let img = this.getImage(id, profile);
    if(!img.indexByTransform.hasOwnProperty(transform))
      throw new Error(`BronzeHelper: transform ${transform} not present for image ${id} in profile ${profile}.`);

    let r = [];
    for(const format in img.indexByTransform[transform]) {
      const index = img.indexByTransform[transform][format];
      r.push(img.versions[index]);
    }

    return r;
  }
}

module.exports = BronzeHelper;
